### ISSUE TITLE
Build failure in Http Directory Service: 3 tests systematically failing in HttpDirectoryServiceIT on my Windows laptop

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#682] opened 2016-08-23 21:20 UTC
When I build latest gateway from develop branch (commit 8013a4b73 Aug 23) I am systematically getting 3 test failures in HttpDirectoryServiceIT:

```
Results :

Failed tests:
  HttpDirectoryServiceIT.shouldFollowSymLinksIfRestrictedInsideBaseFolder Specified behavior did not match expected:<...flush

read status "[200" "OK"
read version "HTTP/1.1"

close
closed]
> but was:<...flush

read status "[404"]
>
  HttpDirectoryServiceIT.shouldFollowSymLinksInsideBaseFolder Specified behavior did not match expected:<...flush

read status "[200" "OK"
read version "HTTP/1.1"

close
closed]
> but was:<...flush

read status "[404"]
>
  HttpDirectoryServiceIT.shouldFollowSymLinksOutsideBaseFolder Specified behavior did not match expected:<...flush

read status "[200" "OK"
read version "HTTP/1.1"

close
closed]
> but was:<...flush

read status "[404"]
>
```

Full output from the build (run using command mvn clean install -rf :gateway.service.http.directory) is here:
[out.HttpDirectoryServiceIT.shouldFollowSymLinksOutsideBaseFolder.fail.txt](https://github.com/kaazing/gateway/files/433588/out.HttpDirectoryServiceIT.shouldFollowSymLinksOutsideBaseFolder.fail.txt)

**Comment by mgherghe** [comment] 2016-08-24 10:20
This seems to be a duplicate of [issue #694](https://github.com/kaazing/tickets/issues/694).

**Closed** 2016-11-16 23:20 UTC
Labels: bug
