### ISSUE TITLE
javadoc errors in Gateway

### ISSUE THREAD

**Issue by krismcqueen** [kaazing/gateway#152] opened 2015-05-21 01:07 UTC
I ran the following command on gateway:

mvn org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar

With Java 8 the following errors occurred.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (default-cli) on project gateway.resource.address: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactory.java:139: warning: no @param for location
[ERROR] public ResourceAddress newResourceAddress(URI location, ResourceOptions options) {
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactory.java:149: warning: no @param for location
[ERROR] public ResourceAddress newResourceAddress(URI location,
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactory.java:149: warning: no @param for qualifier
[ERROR] public ResourceAddress newResourceAddress(URI location,
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:66: warning: no @return
[ERROR] public abstract String getSchemeName();
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:80: warning: no @param for location
[ERROR] public final T newResourceAddress(URI location,
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:80: warning: no @param for optionsByName
[ERROR] public final T newResourceAddress(URI location,
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:80: warning: no @param for optionsFactory
[ERROR] public final T newResourceAddress(URI location,
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:80: warning: no @return
[ERROR] public final T newResourceAddress(URI location,
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:339: warning: no @return
[ERROR] protected abstract String getTransportName();
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:423: error: unterminated signature
[ERROR] \* These options are removed and set in {@link #parseNamedOptions(java.net.URI, ResourceOptions, java.util.Map }
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:428: warning: no @param for options
[ERROR] protected Map<String, Object> getNewOptionsByName(ResourceOptions options, Map<String, Object> optionsByName) {
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:428: warning: no @param for optionsByName
[ERROR] protected Map<String, Object> getNewOptionsByName(ResourceOptions options, Map<String, Object> optionsByName) {
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:428: warning: no @return
[ERROR] protected Map<String, Object> getNewOptionsByName(ResourceOptions options, Map<String, Object> optionsByName) {
[ERROR] ^
[ERROR] /home/kmcqueen/kaazing/github/gateway/resource.address/spi/src/main/java/org/kaazing/gateway/resource/address/ResourceAddressFactorySpi.java:428: warning - Tag @link: malformed: "#parseNamedOptions(java.net.URI, ResourceOptions, java.util.Map "

**Comment by dpwspoon** [comment] 2015-05-21 16:31
I believe the java doclint is the is the cause of those errors.  See this
article
<http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html>.
We could turn it off but in the long run it is probably better to clean it
up.

Satish or Brennan perhaps we can prioritize this / file a story or task.

- David

**Comment by sbadugu** [comment] 2016-11-16 23:57
Duplicate of #157

**Closed by sbadugu** 2016-11-16 23:57 UTC
Labels: duplicate
